export enum ErrorCode {
  // Auth errors
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',

  // Resource errors
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',

  // Booking errors
  ROOM_NOT_AVAILABLE = 'ROOM_NOT_AVAILABLE',
  OVERBOOKING_DETECTED = 'OVERBOOKING_DETECTED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
  CHECKIN_BEFORE_TODAY = 'CHECKIN_BEFORE_TODAY',
  CHECKOUT_BEFORE_CHECKIN = 'CHECKOUT_BEFORE_CHECKIN',

  // Payment errors
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  OVERPAYMENT = 'OVERPAYMENT',
  REFUND_EXCEEDS_PAID = 'REFUND_EXCEEDS_PAID',

  // Rate errors
  RATE_NOT_FOUND = 'RATE_NOT_FOUND',
  RATE_NOT_APPLICABLE = 'RATE_NOT_APPLICABLE',
  RATE_CONFLICT = 'RATE_CONFLICT',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Channel Manager
  CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
  CHANNEL_SYNC_FAILED = 'CHANNEL_SYNC_FAILED',
  CHANNEL_NOT_CONFIGURED = 'CHANNEL_NOT_CONFIGURED',
  CHANNEL_AUTH_FAILED = 'CHANNEL_AUTH_FAILED',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',

  // Guest errors
  GUEST_NOT_FOUND = 'GUEST_NOT_FOUND',
  GUEST_DUPLICATE_PHONE = 'GUEST_DUPLICATE_PHONE',

  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
